# Generated by Django 4.2.7 on 2023-11-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('email_address', models.EmailField(blank=True, max_length=150)),
                ('message', models.CharField(blank=True, max_length=150)),
            ],
        ),
    ]
